### ISSUE TITLE
NoReverseMatch {% url 'cartoview_proxy' 'geoserver' '' %}

### ISSUE THREAD

**Issue by khaledboka** [cartologic/cartoview_simple_catalog#5]
After installing the app tried to make a new instance 

<img width="955" alt="screen shot 2017-11-28 at 10 48 19 am" src="https://user-images.githubusercontent.com/13452248/33310267-b7671954-d429-11e7-92af-40e39f7b442f.png">

current cartoview commit:
https://github.com/cartologic/cartoview/commit/636c9154719529bbf031dc23136ef0ece344f559

**Comment by hishamkaram** [comment]
fixed
